name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "baybayy"
      - name: run 2 echo command together
        run: | 
          echo "first output"
          echo "second output"

            
